#############################
#                           #
#       Plex Velocity       #
#           v1.1            #
#                           #
#############################

[server]
name = "Plexus"

# Placeholders
# %mcversion% - The Velocity Version (i.e. 3.1.2-SNAPSHOT)
# %servername% - The name provided above
# %randomgradient% - Creates a random gradient every ping of two random colors for the whole string
# Supports MiniMessage strings, no legacy & and ยง
motd = ["%randomgradient%%servername% - %mcversion%", "Another motd"]
colorizeMotd = false

# Enables debug messages
debug = false

# Due to game code only supporting legacy color codes for
# player samples and not components, you may only use ยง or & here
# for colors.
sample = ["example", "example"]

# Adds this amount to the current player count
add-player-count = 0

# The max player count will always display as +1 more than the player count
plus-one-max-count = true